orbs:
  aws-ecr: circleci/aws-ecr@1.0.0
version: 2.1
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build_and_push_image:
          account-url: ${AWS_ECR_ACCOUNT_URL}
          aws-access-key-id: ${ACCESS_KEY_ID}
          aws-secret-access-key: ${SECRET_ACCESS_KEY}
          context: myContext
          create-repo: true
          dockerfile: myDockerfile
          path: pathToMyDockerfile
          profile-name: myProfileName
          region: ${AWS_REGION}
          repo: myECRRepository
          tag: myECRRepoTag
