orbs:
  aws-ecr: circleci/aws-ecr@1.0.0
version: 2.1
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build_and_push_image:
<<<<<<< Updated upstream
          account-url: ${AWS_ECR_ACCOUNT_URL}
          aws-access-key-id: ${ACCESS_KEY_ID}
          aws-secret-access-key: ${SECRET_ACCESS_KEY}
=======
          account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
          aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
          aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
>>>>>>> Stashed changes
          context: myContext
          create-repo: true
          dockerfile: myDockerfile
          path: pathToMyDockerfile
          profile-name: myProfileName
<<<<<<< Updated upstream
          region: ${AWS_REGION}
=======
          region: AWS_REGION_ENV_VAR_NAME
>>>>>>> Stashed changes
          repo: myECRRepository
          tag: myECRRepoTag
