apiVersion: v1
kind: Service
metadata:
  name: node-lanebreach-backend
  labels:
    app: node-lanebreach
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: node-lanebreach
    tier: backend
  ports:
  - port: 3000
    targetPort: http-server
