apiVersion: v1
kind: Service
metadata:
  name: node-lanebreach-frontend
  labels:
    app: node-lanebreach
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    app: node-lanebreach
    tier: frontend
  ports:
  - port: 8080
    targetPort: http-server